// Copyright (c) 2026 MeeJoy

// Mock data constants for browser development

export const MOCK_CONFIG = {
  theme: 'system',
  language: 'zh',
  current_agent: 'hermes-agent',
  gateway_host: '127.0.0.1',
  gateway_port: 8642,
  user_nickname: '',
  workspace_path: '~/AI/hermes-workspace',
  workspaces: [
    { id: 'default', name: '默认工作区', path: '~/AI/hermes-workspace', icon: '📁' }
  ]
}

export const MOCK_SESSIONS = [
  { id: '1', title: '欢迎使用 Hermes', pinned: false, updated_at: Date.now(), model: 'MiniMax-M2.7' }
]

export const MOCK_SKILLS = [
  {
    name: 'plan',
    description: 'Plan mode for Hermes — inspect context and write a concrete plan without executing work.',
    category: 'software-development',
    enabled: true,
    source: 'builtin',
    trust: 'builtin',
    identifier: null,
    version: '1.0.0',
    tags: ['planning', 'workflow'],
    path: '~/.hermes/skills/software-development/plan/SKILL.md',
  },
  {
    name: 'github-pr-workflow',
    description: 'Guide the full GitHub pull request workflow with review and merge checkpoints.',
    category: 'github',
    enabled: true,
    source: 'builtin',
    trust: 'builtin',
    identifier: null,
    version: '1.0.0',
    tags: ['github', 'pull-request'],
    path: '~/.hermes/skills/github/github-pr-workflow/SKILL.md',
  },
  {
    name: 'codex-style-ui-redesign',
    description: 'Redesign a UI to match Codex/Claude Code style when reference images are unavailable.',
    category: 'design',
    enabled: true,
    source: 'local',
    trust: 'local',
    identifier: null,
    version: null,
    tags: ['ui-design', 'codex-style'],
    path: '~/.hermes/skills/codex-style-ui-redesign/SKILL.md',
  },
]

export const MOCK_TOOLSETS = [
  {
    name: 'web',
    label: 'Web Search & Scraping',
    description: 'Web Search & Scraping',
    enabled: true,
    configured: true,
    tools: [],
  },
  {
    name: 'browser',
    label: 'Browser Automation',
    description: 'Browser Automation',
    enabled: true,
    configured: true,
    tools: [],
  },
  {
    name: 'skills',
    label: 'Skills',
    description: 'Skills',
    enabled: true,
    configured: true,
    tools: [],
  },
]

export const MOCK_CRON_JOBS = [
  {
    id: 'cron-demo-1',
    name: '每日总结',
    prompt: '整理今天的重要进展，输出一份简明总结。',
    schedule: {
      kind: 'cron',
      expr: '0 18 * * *',
      display: '0 18 * * *',
    },
    schedule_display: '0 18 * * *',
    enabled: true,
    state: 'scheduled',
    deliver: 'local',
    last_run_at: null,
    next_run_at: null,
    last_error: null,
  },
]

export const MOCK_ENV_VARS = {
  // Nous
  NOUS_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Nous Portal API key',
    url: 'https://portal.nousresearch.com/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  // OpenAI
  OPENAI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'OpenAI API key',
    url: 'https://platform.openai.com/api-keys',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  OPENAI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'OpenAI base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  OPENAI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default OpenAI model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Anthropic
  ANTHROPIC_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Anthropic API key',
    url: 'https://console.anthropic.com/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  ANTHROPIC_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Anthropic base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  ANTHROPIC_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Anthropic model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // DashScope (Qwen)
  DASHSCOPE_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Alibaba Cloud DashScope API key (Qwen + multi-provider models)',
    url: 'https://modelstudio.console.alibabacloud.com/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  DASHSCOPE_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'DashScope base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  DASHSCOPE_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default DashScope model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Hermes Qwen
  HERMES_QWEN_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Hermes Qwen API key',
    url: 'https://modelstudio.console.alibabacloud.com/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  HERMES_QWEN_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Hermes Qwen base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  HERMES_QWEN_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Hermes Qwen model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // DeepSeek
  DEEPSEEK_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'DeepSeek API key for direct DeepSeek access',
    url: 'https://platform.deepseek.com/api_keys',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  DEEPSEEK_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'DeepSeek base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  DEEPSEEK_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default DeepSeek model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Google (Gemini)
  GOOGLE_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Google AI Studio API key',
    url: 'https://aistudio.google.com/app/apikey',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  GOOGLE_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Google base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  GOOGLE_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Google model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Gemini (duplicate of Google but separate entry)
  GEMINI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Gemini API key',
    url: 'https://aistudio.google.com/app/apikey',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  GEMINI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Gemini base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  GEMINI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Gemini model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // GLM / Z.AI
  GLM_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'GLM / Z.AI API key',
    url: 'https://open.bigmodel.cn/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  GLM_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'GLM base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  GLM_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default GLM model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // ZAI
  ZAI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Z.AI API key',
    url: 'https://open.bigmodel.cn/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  ZAI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Z.AI base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  ZAI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Z.AI model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Z-ai
  Z_AI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Z.AI API key',
    url: 'https://open.bigmodel.cn/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  Z_AI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Z.AI base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  Z_AI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Z.AI model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Hugging Face
  HF_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Hugging Face API token',
    url: 'https://huggingface.co/settings/tokens',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  HF_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Hugging Face base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  HF_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Hugging Face model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Kimi / Moonshot
  KIMI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Kimi / Moonshot API key',
    url: 'https://platform.moonshot.cn/console/api-keys',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  KIMI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Kimi base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  KIMI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Kimi model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // MiniMax (China)
  MINIMAX_CN_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'MiniMax (China) API key',
    url: 'https://platform.minimaxi.com/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  MINIMAX_CN_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'MiniMax base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  MINIMAX_CN_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default MiniMax model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // MiniMax
  MINIMAX_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'MiniMax API key',
    url: 'https://www.minimax.io/platform/user-center/basic-information/interface-key',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  MINIMAX_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'MiniMax base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  MINIMAX_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default MiniMax model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // OpenRouter
  OPENROUTER_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'OpenRouter API key',
    url: 'https://openrouter.ai/keys',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: true,
  },
  OPENROUTER_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'OpenRouter base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  OPENROUTER_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default OpenRouter model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Xiaomi MiMo
  XIAOMI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Xiaomi MiMo API key',
    url: null,
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  XIAOMI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'Xiaomi MiMo base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  XIAOMI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default Xiaomi MiMo model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // xAI
  XAI_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'xAI API key',
    url: 'https://console.x.ai/',
    category: 'provider',
    is_password: true,
    tools: [],
    advanced: false,
  },
  XAI_BASE_URL: {
    is_set: false,
    redacted_value: null,
    description: 'xAI base URL override',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: true,
  },
  XAI_DEFAULT_MODEL: {
    is_set: false,
    redacted_value: null,
    description: 'Default xAI model',
    url: null,
    category: 'provider',
    is_password: false,
    tools: [],
    advanced: false,
  },
  // Exa (tool, not provider - but kept for compatibility)
  EXA_API_KEY: {
    is_set: false,
    redacted_value: null,
    description: 'Exa API key for AI-native web search and contents',
    url: 'https://exa.ai/',
    category: 'tool',
    is_password: true,
    tools: ['web_search', 'web_extract'],
    advanced: false,
  },
}

export const MOCK_LOG_LINES = {
  agent: [
    '2026-04-21 03:02:44,399 INFO gateway.platforms.api_server: API server listening on http://127.0.0.1:8642',
    '2026-04-21 03:02:45,156 INFO gateway.run: Gateway running with 2 platform(s)',
    '2026-04-21 03:02:45,172 INFO gateway.run: Cron ticker started (interval=60s)',
    '2026-04-21 03:05:59,931 WARNING aiohttp.access: GET / returned 404 from localhost:5173',
    '2026-04-21 03:06:08,277 ERROR aiohttp.access: OPTIONS /v1/responses returned 403 from localhost:5173',
  ],
  errors: [
    '2026-04-21 03:06:08,277 ERROR aiohttp.access: OPTIONS /v1/responses returned 403',
    '2026-04-21 03:06:08,278 ERROR gateway.proxy: Browser preflight rejected because CORS is disabled',
  ],
  gateway: [
    '2026-04-21 03:02:44,400 INFO gateway.run: Connecting to qqbot...',
    '2026-04-21 03:02:45,147 INFO gateway.platforms.qqbot: Connected',
    '2026-04-21 03:02:45,171 INFO gateway.run: Channel directory built: 2 target(s)',
  ],
}
